Algoritmo "INTEIRO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/02/2024
Var
// Seção de Declarações das variáveis 



A, B, C: INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc..

        ESCREVA ("DIGITE UM NUMERO: ")
        LEIA (A)
        ESCREVA ("DIGITE OUTRO NUMERO: ")
        LEIA (B)
        C<-A+B
        ESCREVA (C)
        
        
Fimalgoritmo